import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Linktree",
  description: "Generated by Ali Tarichi",
};

interface RootLayoutProps {
  children: React.ReactNode; // Properly typing the children prop
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`bg-custom-gradient ${outfit.className}`}>
        {children}
      </body>
    </html>
  );
}
